const locations=[
 {id:'D-04',name:'Drain D-04 · Lake North',state:'Telangana',region:'South India',city:'Hyderabad',water:'Lake North',x:49,y:42,base:79,catchment:88,traffic:82,construction:73,waste:61,confidence:72,arrival:'2h 40m',action:'Inspect + temporary screen',status:'Pending',summary:'Large paved catchment and high traffic exposure connect this drain to Lake North before heavy rain.'},
 {id:'D-11',name:'Outfall D-11 · Bellandur edge',state:'Karnataka',region:'South India',city:'Bengaluru',water:'Bellandur Lake',x:47,y:57,base:76,catchment:84,traffic:77,construction:62,waste:73,confidence:68,arrival:'3h 10m',action:'Inspect + sample water',status:'Pending',summary:'High waste activity and a large paved catchment increase the priority of this outfall.'},
 {id:'D-02',name:'Drain D-02 · Yamuna Link',state:'Delhi',region:'North India',city:'Delhi',water:'Yamuna floodplain',x:54,y:23,base:72,catchment:69,traffic:91,construction:65,waste:58,confidence:81,arrival:'1h 55m',action:'Clean inlet',status:'Protected',summary:'Heavy traffic exposure and fast rainfall arrival make early inspection valuable.'},
 {id:'D-07',name:'Outfall D-07 · Mithi corridor',state:'Maharashtra',region:'West India',city:'Mumbai',water:'Mithi River',x:41,y:34,base:70,catchment:80,traffic:86,construction:52,waste:68,confidence:77,arrival:'2h 05m',action:'Inspect + clean',status:'Pending',summary:'Dense urban surfaces and traffic expose this corridor to a high first-flush load.'},
 {id:'D-15',name:'Drain D-15 · Adyar approach',state:'Tamil Nadu',region:'South India',city:'Chennai',water:'Adyar River',x:59,y:67,base:67,catchment:74,traffic:71,construction:60,waste:56,confidence:65,arrival:'3h 45m',action:'Monitor + inspect',status:'Pending',summary:'A mixed residential catchment drains toward a sensitive river approach.'},
 {id:'D-21',name:'Drain D-21 · East Canal',state:'West Bengal',region:'East & North-East India',city:'Kolkata',water:'East Kolkata Wetlands',x:66,y:41,base:64,catchment:72,traffic:63,construction:54,waste:79,confidence:61,arrival:'4h 20m',action:'Place debris screen',status:'Pending',summary:'Waste activity is the leading risk factor near this wetland-connected drain.'},
 {id:'D-31',name:'Drain D-31 · Jaipur market',state:'Rajasthan',region:'North India',city:'Jaipur',water:'Amanishah drain',x:39,y:28,base:57,catchment:60,traffic:70,construction:49,waste:66,confidence:56,arrival:'5h 05m',action:'Inspect inlet',status:'Pending',summary:'Market waste and paved surfaces create a moderate-to-high priority.'},
 {id:'D-42',name:'Drain D-42 · Guwahati lowland',state:'Assam',region:'East & North-East India',city:'Guwahati',water:'Bharalu River',x:70,y:26,base:52,catchment:63,traffic:45,construction:42,waste:58,confidence:49,arrival:'5h 40m',action:'Monitor',status:'Protected',summary:'Lower traffic exposure, but a lowland connection keeps this point under watch.'}
];
let scenario={dry:18,rain:'heavy',region:'All India'};let actionCount=2;let currentLocation=null;
const $=id=>document.getElementById(id);const riskLabel=score=>score>=80?'very-high':score>=65?'high':score>=45?'medium':'low';
function rainValue(){return {light:8,moderate:24,heavy:62,extreme:110}[scenario.rain]}
function score(loc){const dry=Math.min(100,scenario.dry/18*100);const rain=Math.min(100,rainValue()/62*100);const raw=.25*dry+.20*rain+.15*loc.catchment+.15*loc.traffic+.10*loc.construction+.10*loc.waste+.05*(loc.water?80:40);return Math.round(Math.min(99,raw*.82+loc.base*.18))}
function filtered(){return locations.filter(l=>scenario.region==='All India'||l.region===scenario.region)}
function populateStates(){const states=[...new Set(locations.map(l=>l.state))].sort();$('stateFilter').innerHTML='<option value="all">All states</option>'+states.map(s=>`<option>${s}</option>`).join('')}
function render(){const list=filtered().map(l=>({...l,score:score(l),level:riskLabel(score(l))})).sort((a,b)=>b.score-a.score);const high=list.filter(l=>l.score>=65).length; $('metricDryDays').textContent=`${scenario.dry} days`;$('dryDaysOutput').textContent=`${scenario.dry} days`;$('highRiskCount').textContent=high;$('locationsShown').textContent=list.length;const top=list[0]; if(top){$('topPriorityName').textContent=top.name.split(' · ')[0];$('topPriorityScore').textContent=top.score;$('topPrioritySeverity').textContent=top.level.replace('-',' ').toUpperCase();$('topPrioritySeverity').className=`severity ${top.level}`;$('topPrioritySummary').textContent=top.summary;$('topReasons').innerHTML=[['Dry spell',`${scenario.dry} days`],['Rain forecast',`${rainValue()} mm · ${scenario.rain}`],['Paved catchment',`${top.catchment}/100`],['Traffic exposure',`${top.traffic}/100`]].map(x=>`<div class="reason"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$('openTopPriority').onclick=()=>openDetail(top.id)}renderMap(list);renderQueue(list);updateCoverage()}
function renderMap(list){const map=$('map');map.querySelectorAll('.map-pin').forEach(x=>x.remove());list.forEach(l=>{const pin=document.createElement('button');pin.className=`map-pin ${l.level}`;pin.style.left=`${l.x}%`;pin.style.top=`${l.y}%`;pin.title=`${l.name}: ${l.score}/100`;pin.innerHTML='<span>•</span>';pin.onclick=()=>openDetail(l.id);map.appendChild(pin)})}
function renderQueue(list){const state=$('stateFilter').value,risk=$('riskFilter').value;const view=list.filter(l=>(state==='all'||l.state===state)&&(risk==='all'||l.level===risk));$('queueList').innerHTML=view.map(l=>`<div class="queue-item"><div><h3>${l.name}</h3><p>${l.city}, ${l.state} · ${l.water}</p></div><div class="queue-score"><span class="severity ${l.level}">${l.score}</span><small>relative risk</small></div><div class="queue-action">${l.action}<br><span class="${l.status==='Protected'?'status-done':''}">${l.status}</span></div><button onclick="openDetail('${l.id}')">Inspect</button></div>`).join('')||'<p class="disclaimer">No locations match this filter.</p>'}
function updateCoverage(){const total=locations.length,done=locations.filter(l=>l.status==='Protected').length;const pct=Math.round(done/total*100);$('actionsCount').textContent=actionCount;$('coverageStat').textContent=`${pct}%`;$('coverageBar').style.width=`${pct}%`}
function openDetail(id){const l=locations.find(x=>x.id===id);if(!l)return;currentLocation=l;const s=score(l);$('dialogTitle').textContent=l.name;$('dialogBody').innerHTML=`<div class="detail-meta"><div><small>Relative risk</small><b>${s}/100 · ${riskLabel(s).replace('-',' ')}</b></div><div><small>Rain arrival window</small><b>${l.arrival}</b></div><div><small>Connected water body</small><b>${l.water}</b></div><div><small>Data confidence</small><b>${l.confidence}% · field + fallback</b></div></div><p class="warning-box">${l.summary} This is an estimate for prioritization, not a laboratory result.</p><h3>Factor breakdown</h3><div class="detail-factors">${[['Dry-period accumulation',Math.min(100,scenario.dry/18*100)],['Rainfall intensity',Math.min(100,rainValue()/62*100)],['Paved catchment',l.catchment],['Traffic exposure',l.traffic],['Construction proximity',l.construction],['Waste / animal activity',l.waste]].map(([n,v])=>`<div class="factor-row"><span>${n}</span><div class="factor-bar"><span style="width:${v}%"></span></div><b>${Math.round(v)}</b></div>`).join('')}</div><p class="disclaimer">Source: ${l.status==='Protected'?'field action record + ':'fallback seeded record + '}model estimate. Observation freshness and completeness affect confidence.</p>`;$('detailDialog').showModal()}
function markAction(){if(!currentLocation)return;currentLocation.status='Protected';actionCount++;$('detailDialog').close();render();toast(`${currentLocation.id} marked protected. Priority list updated.`)}
function exportReport(){const list=filtered().map(l=>({...l,score:score(l),level:riskLabel(score(l))})).sort((a,b)=>b.score-a.score);const rows=[['FirstFlush India priority report'],['Generated',new Date().toISOString()],['Region',scenario.region],['Dry spell',`${scenario.dry} days`],['Rainfall',`${rainValue()} mm (${scenario.rain})`],[],['ID','Location','State','City','Risk','Level','Recommended action','Status'] ,...list.map(l=>[l.id,l.name,l.state,l.city,l.score,l.level,l.action,l.status])];const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='firstflush-priority-report.csv';a.click();toast('Priority report downloaded.');}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
$('dryDays').oninput=e=>{scenario.dry=+e.target.value;render()};$('rainSelect').onchange=e=>{scenario.rain=e.target.value;render()};$('regionSelect').onchange=e=>{scenario.region=e.target.value;render()};$('stateFilter').onchange=renderQueue;$('riskFilter').onchange=renderQueue;$('resetButton').onclick=()=>{scenario={dry:18,rain:'heavy',region:'All India'};$('dryDays').value=18;$('rainSelect').value='heavy';$('regionSelect').value='All India';render();toast('Assessment context reset.')};$('runScenario').onclick=()=>{scenario={dry:18,rain:'heavy',region:'All India'};$('dryDays').value=18;$('rainSelect').value='heavy';$('regionSelect').value='All India';render();document.querySelector('#priorities').scrollIntoView({behavior:'smooth'});toast('Risk assessment completed for the heavy-rain scenario.')};$('howItWorks').onclick=()=>$('methodDialog').showModal();$('helpButton').onclick=()=>$('methodDialog').showModal();$('reportButton').onclick=exportReport;$('observationButton').onclick=()=>$('observationDialog').showModal();$('dialogAction').onclick=markAction;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('observationForm').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target);locations.push({id:`OBS-${locations.length+1}`,name:data.get('name'),state:data.get('state'),region:'South India',city:'Field observation',water:'To be verified',x:25+Math.random()*50,y:20+Math.random()*55,base:58,catchment:55,traffic:50,construction:45,waste:data.get('condition').includes('Blocked')?80:40,confidence:25,arrival:'Pending forecast',action:'Verify observation',status:'Pending',summary:data.get('notes')||'Community observation awaiting verification.'});e.target.reset();$('observationDialog').close();populateStates();render();toast('Observation saved as pending verification.')};
populateStates();render();
