const $=id=>document.getElementById(id);const ui={items:[],scenario:{dryDays:18,rainfall:'heavy',region:'All India'},current:null};const rainfall={light:8,moderate:24,heavy:62,extreme:110};
function qs(){return new URLSearchParams({dryDays:ui.scenario.dryDays,rainfall:ui.scenario.rainfall,region:ui.scenario.region,state:$('state').value,city:$('city').value,risk:$('risk').value}).toString()}
function toast(text){const t=$('toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),3000)}
async function api(url,options){const r=await fetch(url,options);const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Request failed');return body}
function setStatus(mode,label){const el=$('systemStatus');el.textContent=label;el.className=`status-pill ${mode}`}
function populate(items){const states=[...new Set(items.map(x=>x.state))].sort();const cities=[...new Set(items.map(x=>x.city))].sort();const selectedState=$('state').value,selectedCity=$('city').value;$('state').innerHTML='<option value="all">All states</option>'+states.map(x=>`<option>${x}</option>`).join('');$('city').innerHTML='<option value="all">All cities</option>'+cities.map(x=>`<option>${x}</option>`).join('');if(states.includes(selectedState))$('state').value=selectedState;if(cities.includes(selectedCity))$('city').value=selectedCity}
function pinPosition(item){return {x:110+(Number(item.lon)-68)*8.1,y:70+(30-Number(item.lat))*13.3}}
function renderMap(){const pins=$('pins');pins.innerHTML='';ui.items.forEach(item=>{const p=pinPosition(item);const circle=document.createElementNS('http://www.w3.org/2000/svg','circle');circle.setAttribute('cx',p.x);circle.setAttribute('cy',p.y);circle.setAttribute('r',item.score>=80?9:7);circle.setAttribute('class',`map-pin pin-${item.level==='very-high'?'vh':item.level==='high'?'hi':item.level==='medium'?'me':'lo'}`);circle.setAttribute('tabindex','0');circle.setAttribute('aria-label',`${item.name}, score ${item.score}`);circle.onclick=()=>openDetail(item.id);circle.onkeydown=e=>{if(e.key==='Enter')openDetail(item.id)};pins.appendChild(circle)})}
function render(){const items=ui.items;const high=items.filter(x=>x.score>=65).length;const avg=items.length?Math.round(items.reduce((a,x)=>a+x.confidence,0)/items.length):0;$('locationCount').textContent=items.length;$('highCount').textContent=high;$('confidence').textContent=`${avg}%`;$('actionCount').textContent=items.reduce((n,x)=>n+(x.status==='Protected'?1:0),0);const top=items[0];if(!top)return;$('heroRisk').textContent=top.score;$('topName').textContent=top.name;$('topScore').textContent=top.score;$('topSummary').textContent=`${top.city}, ${top.state} · connected to ${top.waterBody}. ${top.provenance?.note||'Estimate uses current scenario factors.'}`;$('topReasons').innerHTML=[['Dry spell',`${ui.scenario.dryDays} days`],['Rainfall',`${rainfall[ui.scenario.rainfall]} mm`],['Catchment',`${top.catchment}/100`],['Traffic',`${top.traffic}/100`]].map(x=>`<div class="reason"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$('topOpen').onclick=()=>openDetail(top.id);$('coverage').textContent=`${items.length} monitored · source: API`;renderMap();$('queueList').innerHTML=items.map(x=>`<div class="queue-item"><div><h3>${x.name}</h3><p>${x.city}, ${x.state} · ${x.waterBody}</p></div><div class="queue-score"><b>${x.score}</b><small>${x.level}</small></div><div class="queue-action">${x.recommendedAction||'Inspect'}<br><small>${x.status||'Pending'}</small></div><button onclick="openDetail('${x.id}')">Inspect</button></div>`).join('')||'<div class="loading">No matching locations.</div>'}
async function load(){try{setStatus('pending','Refreshing…');const data=await api(`/api/locations?${qs()}`);ui.items=data.items;populate(data.items);render();const weather=await api(`/api/weather?lat=17.385&lon=78.486`);$('weatherMode').textContent=weather.mode==='live'?'Live weather provider':'Fallback weather mode';$('weatherSource').textContent=`${weather.source} · ${new Date(weather.updatedAt).toLocaleTimeString('en-IN')}`;$('weatherSignal').className=`signal-dot ${weather.mode==='live'?'':'fallback'}`;$('lastUpdated').textContent=`Updated ${new Date(data.updatedAt).toLocaleTimeString('en-IN')}`;setStatus(weather.mode==='live'?'':'pending',weather.mode==='live'?'Live':'Fallback');}catch(e){setStatus('offline','Offline');toast(e.message)}}
async function openDetail(id){try{const x=await api(`/api/locations/${id}?dryDays=${ui.scenario.dryDays}&rainfall=${ui.scenario.rainfall}`);ui.current=x;$('detailTitle').textContent=x.name;$('detailBody').innerHTML=`<div class="detail-meta"><div><small>Relative risk</small><b>${x.score}/100 · ${x.level}</b></div><div><small>Confidence</small><b>${x.confidence}%</b></div><div><small>Water body</small><b>${x.waterBody}</b></div><div><small>Provenance</small><b>${x.source}</b></div></div><p class="notice">${x.source}. This score supports prioritization; it is not a laboratory result.</p><h3>Factor breakdown</h3>${Object.entries({dryDays:Math.min(100,ui.scenario.dryDays/18*100),rainfall:Math.min(100,rainfall[ui.scenario.rainfall]/62*100),catchment:x.catchment,traffic:x.traffic,construction:x.construction,waste:x.waste}).map(([k,v])=>`<div class="factor-row"><span>${k}</span><div class="factor-bar"><span style="width:${v}%"></span></div><b>${Math.round(v)}</b></div>`).join('')}<div class="history"><h3>Action history</h3>${(x.actions||[]).map(a=>`<div class="history-item"><b>${a.actionType}</b><small>${new Date(a.createdAt).toLocaleString('en-IN')} · ${a.actor}</small></div>`).join('')||'<small>No actions recorded yet.</small>'}</div><label>Action<select id="actionType"><option>Inspect</option><option>Clean</option><option>Temporary screen / diversion</option><option>Sample water</option><option>Monitor</option></select></label><label>Note<textarea id="actionNote" rows="2"></textarea></label>`;$('detail').showModal()}catch(e){toast(e.message)}}
async function saveAction(){if(!ui.current)return;try{await api(`/api/locations/${ui.current.id}/actions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({actionType:$('actionType').value,notes:$('actionNote').value})});$('detail').close();toast('Action saved to the API.');load()}catch(e){toast(e.message)}}
async function submitObservation(e){e.preventDefault();try{await api('/api/observations',{method:'POST',body:new FormData(e.target)});$('observation').close();e.target.reset();toast('Observation saved as pending verification.');load()}catch(err){toast(err.message)}}
function addChat(text,who){const box=$('chatMessages');const div=document.createElement('div');div.className=who==='user'?'user-msg':'assistant-msg';div.textContent=text;box.appendChild(div);box.scrollTop=box.scrollHeight}
async function chat(e){e.preventDefault();const input=$('chatInput');const text=input.value.trim();if(!text)return;addChat(text,'user');input.value='';try{const result=await api('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:text,scenario:ui.scenario,locationId:ui.current?.id})});addChat(result.answer,'assistant')}catch(err){addChat(`I could not reach the assistant: ${err.message}`,'assistant')}}
function bind(){['chatOpen','chatOpen2'].forEach(id=>$(id).onclick=()=>$('chat').showModal());$('refresh').onclick=load;$('export').onclick=()=>window.open(`/api/reports/priority.csv?${qs()}`,'_blank');$('dry').oninput=e=>{ui.scenario.dryDays=Number(e.target.value);$('dryOut').textContent=`${ui.scenario.dryDays} days`;load()};$('rain').onchange=e=>{ui.scenario.rainfall=e.target.value;load()};$('region').onchange=e=>{ui.scenario.region=e.target.value;$('state').value='all';$('city').value='all';load()};['state','city','risk'].forEach(id=>$(id).onchange=load);$('reset').onclick=()=>{ui.scenario={dryDays:18,rainfall:'heavy',region:'All India'};$('dry').value=18;$('rain').value='heavy';$('region').value='All India';load()};$('topOpen').onclick=()=>{};$('saveAction').onclick=saveAction;$('observationOpen').onclick=()=>$('observation').showModal();$('observationForm').onsubmit=submitObservation;$('chatForm').onsubmit=chat;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('method').onclick=()=>$('methodology').scrollIntoView({behavior:'smooth'})}
bind();$('dryOut').textContent='18 days';load();setInterval(load,20000);