import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import multer from 'multer';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {readStore, writeStore} from './store.js';
import {enrich, rainfallMm} from './risk.js';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const dataFile = path.resolve(root, process.env.DATA_FILE || 'data/runtime.json');
const upload = multer({dest:path.join(root,'uploads'), limits:{fileSize:5*1024*1024}, fileFilter:(_req,file,cb)=>cb(null, /^image\/(jpeg|png|webp|gif)$/.test(file.mimetype))});
const app = express();
app.disable('x-powered-by');
app.use(cors({origin:(process.env.CORS_ORIGIN || 'http://localhost:8787').split(',')}));
app.use(express.json({limit:'512kb'}));
app.use(express.static(root));
const rate = new Map();
function limit(req,res,next){const key=`${req.ip}:${req.path}`, now=Date.now(), recent=(rate.get(key)||[]).filter(t=>now-t<60000); if(recent.length>=30)return res.status(429).json({error:'Rate limit exceeded'}); recent.push(now); rate.set(key,recent); next();}
function scenario(q){return {dryDays:Number(q.dryDays||18), rainfall:q.rainfall||'heavy'};}
function filtered(items,q){return items.filter(x=>(!q.region||q.region==='All India'||x.region===q.region)&&(!q.state||q.state==='all'||x.state===q.state)&&(!q.city||q.city==='all'||x.city===q.city)&&(!q.risk||q.risk==='all'||enrich(x,scenario(q)).level===q.risk));}

app.get('/api/health', async (_req,res)=>{const data=await readStore(dataFile);res.json({status:'ok',time:new Date().toISOString(),persistence:'local-json',weather:'open-meteo-ready-fallback',ai:process.env.AI_PROVIDER||'local',locations:data.locations.length});});
app.get('/api/locations', async (req,res)=>{const data=await readStore(dataFile); const items=filtered(data.locations,req.query).map(x=>enrich(x,scenario(req.query))).sort((a,b)=>b.score-a.score); res.json({items,scenario:scenario(req.query),updatedAt:new Date().toISOString(),source:'Fallback seed records; replace with verified observations'});});
app.get('/api/locations/:id', async (req,res)=>{const data=await readStore(dataFile), item=data.locations.find(x=>x.id===req.params.id); if(!item)return res.status(404).json({error:'Location not found'}); res.json({...enrich(item,scenario(req.query)),actions:data.actions.filter(a=>a.locationId===item.id),observations:data.observations.filter(o=>o.locationId===item.id)});});
app.post('/api/locations/:id/actions',limit,async(req,res)=>{const data=await readStore(dataFile), item=data.locations.find(x=>x.id===req.params.id); if(!item)return res.status(404).json({error:'Location not found'}); const actionType=String(req.body.actionType||'').trim(); if(!['Inspect','Clean','Temporary screen / diversion','Sample water','Monitor'].includes(actionType))return res.status(400).json({error:'Invalid action'}); const action={id:crypto.randomUUID(),locationId:item.id,actionType,notes:String(req.body.notes||'').slice(0,500),createdAt:new Date().toISOString(),actor:'local operator'}; data.actions.push(action); await writeStore(dataFile,data); res.status(201).json(action);});
app.post('/api/observations',limit,upload.single('photo'),async(req,res)=>{const required=['name','state','condition']; if(required.some(k=>!String(req.body[k]||'').trim()))return res.status(400).json({error:'name, state and condition are required'}); const data=await readStore(dataFile); const observation={id:`OBS-${Date.now()}`,locationId:null,name:String(req.body.name).slice(0,120),state:String(req.body.state).slice(0,80),condition:String(req.body.condition).slice(0,80),notes:String(req.body.notes||'').slice(0,500),photo:req.file?`/uploads/${req.file.filename}`:null,verificationStatus:'Pending verification',createdAt:new Date().toISOString()}; data.observations.push(observation); data.locations.push({id:observation.id,name:observation.name,city:'Field observation',state:observation.state,region:'South India',lat:17.4,lon:78.4,waterBody:'To be verified',catchment:55,traffic:50,construction:45,waste:observation.condition.toLowerCase().includes('blocked')?80:40,base:58,confidence:25,source:'Community field observation · pending verification'}); await writeStore(dataFile,data); res.status(201).json(observation);});
app.get('/api/weather', async(req,res)=>{const lat=Number(req.query.lat||17.385), lon=Number(req.query.lon||78.486); try {const response=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&hourly=precipitation_probability,precipitation&forecast_days=1&timezone=auto`); if(!response.ok)throw new Error('provider unavailable'); const json=await response.json(); res.json({mode:'live',source:'Open-Meteo',updatedAt:new Date().toISOString(),latitude:lat,longitude:lon,nextHours:json.hourly?.precipitation?.slice(0,6)||[],probability:json.hourly?.precipitation_probability?.slice(0,6)||[]});} catch {res.json({mode:'fallback',source:'Fallback scenario',updatedAt:new Date().toISOString(),nextHours:[8,12,24,62],probability:[20,30,55,80]});}});
function answer(message, data){const text=message.toLowerCase(); const top=data.locations.map(x=>enrich(x,{dryDays:18,rainfall:'heavy'})).sort((a,b)=>b.score-a.score)[0]; if(text.includes('why')&&top)return `FirstFlush Copilot: ${top.name} is currently the highest priority at ${top.score}/100 because its paved catchment, traffic exposure, dry-spell accumulation and rainfall context combine into a high relative score. Confidence is ${top.confidence}%. This is a prioritization estimate, not a laboratory result.`; if(text.includes('action')&&top)return `Recommended next action: ${top.action || 'Inspect'} the highest-priority location, record the observation, and consider a temporary screen or water sample where operationally appropriate.`; if(text.includes('fallback')||text.includes('data'))return 'The current national records are fallback seed records. Field observations are marked pending verification. Live weather is labelled separately with its provider and update time.'; return 'I can explain risk factors, identify the next priority, summarize data confidence, recommend field actions, and clarify what FirstFlush does or does not claim.';}
app.post('/api/chat',limit,async(req,res)=>{const message=String(req.body.message||'').trim(); if(!message)return res.status(400).json({error:'message is required'}); const data=await readStore(dataFile); res.json({mode:'local-fallback',answer:answer(message,data),createdAt:new Date().toISOString()});});
app.get('/api/reports/priority.csv',async(req,res)=>{const data=await readStore(dataFile);const rows=filtered(data.locations,req.query).map(x=>enrich(x,scenario(req.query))); const esc=v=>`"${String(v??'').replaceAll('"','""')}"`; const csv=[['FirstFlush India report'],['Generated',new Date().toISOString()],[],['ID','Location','City','State','Risk','Level','Confidence','Source'],...rows.map(x=>[x.id,x.name,x.city,x.state,x.score,x.level,x.confidence,x.source])].map(r=>r.map(esc).join(',')).join('\n');res.type('text/csv').set('Content-Disposition','attachment; filename="firstflush-priority-report.csv"').send(csv);});
app.post('/api/dev/reset',limit,async(_req,res)=>{const {seed}=await import('./store.js');await writeStore(dataFile,structuredClone(seed));res.json({ok:true});});
app.get('*',(_req,res)=>res.sendFile(path.join(root,'index.html')));
app.listen(Number(process.env.PORT||8787),()=>console.log(`FirstFlush running on http://localhost:${process.env.PORT||8787}`));
export {app};
